#!/bin/bash

echo "Give me strating date"
read start_date 
echo "Give ending date"
read end_date
#lastb command shows logs of /var/log/btmp, which contains all the bad login attempts
#with option -s display the state of logins since the specified time
#with options -t display the state of logins until the specified time
sudo lastb -s $start_date -t $end_date

#We search for root in /var/log/auth.log tha contains authentication logs and we overwrite the result in rootMe.txt
grep -e "root" /var/log/auth.log > rootMe.txt

echo All fail-or not attempts are in file rootMe.txt
#We search for failed login attempts in rootMe.txt and the result we overwrite it in the failMe.txt
grep -e "FAILED" rootMe.txt > failMe.txt 

#Create a file with all users
ls /home > users.txt
 
for line in `cat usernames.txt`;
do
	#a is an integer for bad logins
	a=$(grep -e "$line" failMe.txt | wc -l)

	if [ $a -gt 8 ]
	then
	echo -n "Do you want to delete the user : $line (yes or no)?"
	read answer
	 if [ $answer = 'yes' ]
	 then
    	  #with usermod -L (Lock) : lock a user's password
	  usermod -L $line
	 else 
	 echo "User will not be locked"
	 fi
	fi
done

