#!/bin/bash

#Show current system hostname and related info
hostnamectl | grep -e Static -e Operating
#Tells how long the system has been running.
#option -s : system up since, in yyyy-mm-dd HH:MM:SS format
echo To systhma einai anoixto apo tis: 
uptime -s
#List of active users
who --ips


