#!/bin/bash
#εμφανιζουμε το ονομα του εξυπηρετητη οπως και την εκδοση
#του λειτουργικου μας συστηματος
hostnamectl | grep -e Static -e Operating
#Εμφανιζουμε το χρονο που το συστημα μας ειναι ανοιχτο
echo To systhma einai anoixto apo tis: 
uptime -s
#Εμφανιζουμε τον καταλογο των συνδεδεμενων χρηστων αυτη τη στιγμη
who --ips


