#!/bin/bash

#Write users without password in the file UsersWithoutPass.txt
sudo awk -F":" '($2 == "") {print $1}' /etc/shadow > touch  UsersWithoutPass.txt

echo Users without password are:
cat UsersWithoutPass.txt

#Lock the users tha are in the UsersWithoutPass.txt
for line in `cat UsersWithoutPass.txt`; 
do    
    sudo usermod -L $line    
done

