#!/bin/bash

#I'm writing to the /tmp/SUIDfile all files with SUID rights and i list the files with name, permissions and date
sudo find / -perm -4000 -exec ls -ldb {} \; > /tmp/SUIDfile

more /tmp/SUIDfile 
